= CloudBees action: Copy a remote image with Crane

Use this action to copy a remote image from a source to a destination with link:https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane.md[crane], a tool for managing container images.

== Prerequisites

Before invoking the action, you must have a Docker config file in the `${HOME}/.docker/config.json` path. This file is used to authenticate with the Docker registry.

Use either of the below examples to generate a Docker config file.

Use link:https://github.com/cloudbees-io/configure-oci-credentials[the OCI credentials configuration action]:

In your YAML file, add:

[source,yaml]
----

      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.STAGING_DOCKER_REGISTRY }}
          username: ${{ secrets.STAGING_DOCKER_USERNAME }}
          password: ${{ secrets.STAGING_DOCKER_PASSWORD }}

----

Use link:https://github.com/cloudbees-io/configure-ecr-credentials[the ECR credentials configuration action]:

In your YAML file, add:

[source,yaml]
----
      - name: Log in to ECR
        id: login-ecr
        uses: cloudbees-io/configure-ecr-credentials@v1

----

The Docker config file must be formatted in JSON, as follows:

[source,json,role="novalidate"]
----
{
	"auths": {
		"<registry host>": {
			"username": "<username>",
			"password": "<password>",
			"auth": "<username>:<password>"
		}
	}
}
----

If your source and destination registries are different, then you need to include the credential for both registries in the config file, as in the example below:

[source,json,role="novalidate"]
----
{
	"auths": {
		"<registry host>": {
			"username": "<username>",
			"password": "<password>",
			"auth": "<username>:<password>"
		},
		"<destination registry>": {
			"username": "<username>",
			"password": "<password>",
			"auth": "<username>:<password>"
		}
	}
}

----

NOTE: The `+"auth":"<username>:<password>"+` fields must be base64-encoded.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `src`
| String
| Yes
| The source image to copy.

| `destination`
| String
| Yes
| The destination image.

| `platform`
| String
| No
| Specifies the platform in the format `os/arch[/variant][:osversion]`

| `skip-image-validation`
| String
| No
| Default is `true`. When `true`, the source and destination image validation is skipped.
|===

== Usage example

In your YAML file, add:

[source,yaml]
----
      - name: Copy a remote image with Crane
        uses: cloudbees-io/crane@v1
        with:
          src: <source registry>/<image name>:<source image tag>
          destination: <destination registry>/<image name>:<destination image tag>
          platform: linux/amd64
          skip-image-validation: 'false'

----


== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].

