= CloudBees action: Copy a remote image with Crane

Use this action to copy a remote image from a source to a destination with link:https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane.md[crane], a tool for managing container images. This action also reports artifact related data to the workflow run for artifact traceability purposes.

== Prerequisites

Before invoking the action, you must have a Docker config file in the `${HOME}/.docker/config.json` path. This file is used to authenticate with the Docker registry.

Use either of the below actions to generate a Docker config file.

* link:https://github.com/cloudbees-io/configure-oci-credentials[The OCI credentials configuration action].

* link:https://github.com/cloudbees-io/configure-ecr-credentials[The ECR credentials configuration action], for authenticating to an AWS ECR registry. 

NOTE: If your source and destination registries are different, you must authenticate to both registries. Invoke the Docker registry authentication action separately for those registries before invoking the crane action.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `src`
| String
| Yes
| The source image to copy.

| `destination`
| String
| Yes
| The destination image.

| `platform`
| String
| No
| Specifies the platform in the format `os/arch[/variant][:osversion]`

| `skip-image-validation`
| String
| No
| Default is `true`. When `true`, the source and destination image validation is skipped.
|===

== Usage example

In your YAML file, add:

[source,yaml]
----
      - name: Copy a remote image with Crane
        uses: cloudbees-io/crane@v1
        with:
          src: <source registry>/<image name>:<source image tag>
          destination: <destination registry>/<image name>:<destination image tag>
          platform: linux/amd64
          skip-image-validation: 'false'

----


== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].

