apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Action test

on:
  push:
    branches:
    - '**'

jobs:
  test:
    steps:
    - name: Get source code
      uses: cloudbees-io/checkout@v1

    - id: dockerconfig
      name: Configure container registry credentials
      uses: cloudbees-io/configure-oci-credentials@v0
      with:
        registry: ${{ vars.STAGING_DOCKER_REGISTRY }}
        username: ${{ secrets.STAGING_DOCKER_USERNAME }}
        password: ${{ secrets.STAGING_DOCKER_PASSWORD }}

    - id: actionrunmax
      name: Run Action with all inputs specified
      uses: cloudbees-io/crane@SDP-9839
      with:
        src: ubuntu:latest
        destination: ${{ vars.STAGING_DOCKER_REGISTRY }}/staging/ubuntu:dst-test
        platform: linux/amd64
        skip-image-validation: 'false'

    - name: Test Action output maximum
      uses: docker://quay.io/skopeo/stable:v1.13.3
      run: |
        DIGEST="$(skopeo inspect --authfile $HOME/.docker/config.json docker://${{ vars.STAGING_DOCKER_REGISTRY }}/staging/ubuntu:dst-test --format='{{.Digest}}')"
        [ "$DIGEST" = '${{ steps.actionrunmax.outputs.digest }}' ]

    - id: actionrunrequired
      name: Run Action with only required inputs specified
      uses: cloudbees-io/crane@SDP-9839
      with:
        src: alpine:latest
        destination: ${{ vars.STAGING_DOCKER_REGISTRY }}/staging/alpine:dst-test

    - name: Test Action output required inputs
      uses: docker://quay.io/skopeo/stable:v1.13.3
      run: |
        DIGEST="$(skopeo inspect --authfile $HOME/.docker/config.json docker://${{ vars.STAGING_DOCKER_REGISTRY }}/staging/alpine:dst-test --format='{{.Digest}}')"
        [ "$DIGEST" = '${{ steps.actionrunmax.outputs.digest }}' ]

